server:
  port: 9087

#开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: spring-boot-admin-client # 给client应用取个名字
  boot:
    admin:
      client:
        url:  http://localhost:9000   #这里配置admin server 的地址
        username: admin
        password: admin
        instance:
          prefer-ip: true # use ip not use computer name
logging:
  file:
    name: spring-boot-admin-client.log  #配置生成日志文件名称




