server.port: 9600
spring:
  boot:
    admin:
      application:
        name: spring-boot-admin-server
  security:
    user:
      name: admin
      password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS