server:
  port: 8084

spring:
  application:
    name: nacos-admin-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.99.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    path: /app/nacos-admin-server/log