server:
  port: 3333

spring:
  application:
    name: sidecar-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file: sidecar.log

